language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - mkdir cache

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpspec run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
