language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - mkdir cache

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - rm -rf cache
  - mkdir cache
  - vendor/bin/phpspec run
